name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        run: ./gradlew build
        env:
          AE2THINGS_VERSION: ${{ github.event.release.tag_name }}
      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/libs/AE2-Things-${{ github.event.release.tag_name }}.jar
          asset_name: ae2things-${{ github.event.release.tag_name }}.jar
          asset_content_type: application/zip
      - name: Upload to CurseForge
        run: ./gradlew curseforge
        env:
          AE2THINGS_VERSION: ${{ github.event.release.tag_name }}
          CURSEFORGE: ${{ secrets.CURSEFORGE }}
